# Project information
site_name: '50u1w4y'
site_author: '50u1w4y'
site_url: 'https://50u1w4y.github.io'

# Copyright
copyright: 'Copyright &copy; 2019 50u1w4y'

# Configuration
theme:
  name: 'material'
  language: 'en'
  palette:
    primary: 'white'
    accent: 'indigo'
  feature:
    tabs: true


# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - footnotes
  - meta
  - def_list
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Contents
nav:
    - Welcome: index.md
    - HEVD:
        - Home Page: HEVD/homePage.md
        - HEVD 环境搭建: HEVD/buildEnv.md
        - （一）HEVD 栈溢出: HEVD/stackoverflow.md
        - （二）HEVD 任意地址覆盖: HEVD/arbitraryWrite.md
        - （三）HEVD 非换页池溢出: HEVD/nonPagedpooloverflow.md
        - （四）HEVD 空指针引用: HEVD/nullpointerDereference.md
        - （五）HEVD 未初始化栈变量: HEVD/uninitializedStackVariable.md
        - （六）HEVD 未初始化堆变量: HEVD/uninitializedHeapVariable.md
        - （七）HEVD Use After Free: HEVD/useAfterFree.md 
        - bitmap 任意地址写漏洞利用: HEVD/bitmap.md
        - RS1 下 bitmap 的替代方法: HEVD/bitmapReplace_RS1.md
    - 漏洞复现:
        - Home Page: recurrence/homePage.md
        - CVE-2017-0263: recurrence/CVE-2017-0263.md
        - CVE-2021-24074: recurrence/CVE-2021-24074.md
    - 胡说:
        - Home Page: misc/homePage.md
        - mkdocs-material 搭建 gitalk: misc/gitalkBuild.md