# Project information
site_name: '50u1w4y'
site_description: 'A Blog'
site_author: '50u1w4y'
site_url: 'https://50u1w4y.github.io'

# Copyright
copyright: 'Copyright &copy; 2019 50u1w4y'

# Configuration
theme:
  name: 'material'
  language: 'en'
  palette:
    primary: 'white'
    accent: 'indigo'
  feature:
    tabs: true


# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true

# Extensions
#markdown_extensions:
#  - admonition
#  - codehilite:
#      guess_lang: false
#      linenums: false
#  - toc:
#      permalink: true
#  - footnotes
#  - meta
#  - def_list
#  - pymdownx.arithmatex
#  - pymdownx.betterem:
#      smart_enable: all
#  - pymdownx.caret
#  - pymdownx.critic
#  - pymdownx.details
#  - pymdownx.emoji:
#      emoji_generator: !!python/name:pymdownx.emoji.to_png
#  - pymdownx.inlinehilite
#  - pymdownx.magiclink
#  - pymdownx.mark
#  - pymdownx.smartsymbols
#  - pymdownx.superfences
#  - pymdownx.tasklist
#  - pymdownx.tilde


# Contents
nav:
    - Welcome: index.md
    - HEVD:
        - Home Page: HEVD/homePage.md
        - HEVD 环境搭建: HEVD/buildEnv.md
        - （一）HEVD 栈溢出: HEVD/stackoverflow.md