# Project information
site_name: '50u1w4y'
site_description: 'A Blog'
site_author: '50u1w4y'
site_url: 'https://50u1w4y.github.io'

# Copyright
copyright: 'Copyright &copy; 2019 50u1w4y'

# Configuration
theme:
  name: 'material'
  language: 'en'
  palette:
    primary: 'white'
    accent: 'indigo'
  feature:
    tabs: true

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true

# Contents
nav:
    - Welcome:
        - Index Page: index.md