# Project information
site_name: '50u1w4y'
site_description: 'A Blog'
site_author: '50u1w4y'
site_url: 'https://50u1w4y.github.io'

# Copyright
copyright: 'Copyright &copy; 2019 50u1w4y'

# Repository
repo_name: '50u1w4y/50u1w4y.github.io'
repo_url: 'https://github.com/50u1w4y/50u1w4y.github.io'

# Configuration
theme:
  name: 'material'
  language: 'en'
  palette:
    primary: 'white'
    accent: 'indigo'
  feature:
    tabs: true


# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - footnotes
  - meta
  - def_list
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Contents
nav:
    - Welcome: index.md
    - HEVD:
        - Home Page: HEVD/homePage.md
        - HEVD 环境搭建: HEVD/buildEnv.md
        - （一）HEVD 栈溢出: HEVD/stackoverflow.md